server:
  port: 8090
spring:
  hello:
    prefix: "\u5C0F\u635F\u6837"
    suffix: "\u83DC"
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springboot_cache?serverTimezone=GMT%2B8&useSSL=false
  redis:
    host: localhost
#\u9A7C\u5CF0\u547D\u540D\u89C4\u5219
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.haiyuanzi.springboot.cache.mapper: debug
debug: true

